apiVersion: apps/v1
kind: Deployment

metadata:
  name: techtalksapi
  # namespace: aks-part4
  labels:
    run: techtalksapi

spec:
  replicas: 1
  selector:
    matchLabels:
      run: techtalksapi

  template:
    metadata:
      labels:
        run: techtalksapi
    spec:
      initContainers:
        - name: init-myservice
          image: ngacrregistry.azurecr.io/nileshgule/sqlclient
          imagePullPolicy: IfNotPresent
          env:
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlsecret
                key: sapassword
          command:
            - "sh"
            - "-c"
            - "/opt/mssql-tools/bin/sqlcmd -S db-deployment -U sa -P $(SA_PASSWORD) -d master -i initialize-database.sql"
      containers:
      - name: techtalksapi
        image: ngacrregistry.azurecr.io/nileshgule/techtalksapi
        imagePullPolicy: IfNotPresent
        env:
          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:8080
          - name: SA_PASSWORD
            # value: June@2018
            valueFrom:
              secretKeyRef:
                name: sqlsecret
                key: sapassword
          - name: ConnectionStrings__DefaultConnection
            value: "Data Source=db-deployment;Initial Catalog=TechTalksDB;User Id=SA;Password=$(SA_PASSWORD);MultipleActiveResultSets=True"
        ports:
        - containerPort: 8080
          protocol: TCP

      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst